-- Run this once in the Supabase SQL Editor for A&M Hair & Beauty
-- Feedback is written only by the Netlify server function using a server-side Supabase key.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text,
  inquiry text not null check (char_length(inquiry) between 1 and 2000),
  page text,
  viewport text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

-- Explicitly expose only the privileges needed by the server-side service role.
grant usage on schema public to service_role;
grant insert on table public.feedback to service_role;
grant usage, select on sequence public.feedback_id_seq to service_role;

-- Keep browser visitors locked out.
revoke all on table public.feedback from anon, authenticated;
revoke all on sequence public.feedback_id_seq from anon, authenticated;

create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);

-- Refresh the Supabase/PostgREST schema cache so the Data API sees the table immediately.
notify pgrst, 'reload schema';
