-- Run this once in the Supabase SQL Editor for A&M Hair & Beauty
-- Feedback is written only by the Netlify server function using the service-role key.

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 80),
  email text,
  inquiry text not null check (char_length(inquiry) between 1 and 2000),
  page text,
  viewport text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

-- Deliberately no public INSERT/SELECT policy.
-- The service-role key used by the Netlify function bypasses RLS,
-- while visitors cannot read or write the table directly from the browser.

create index if not exists feedback_created_at_idx
  on public.feedback (created_at desc);
