create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('homepage_view','product_view','add_to_cart','checkout_started')),
  visitor_id text,
  path text,
  product_id text,
  quantity integer,
  referrer text,
  created_at timestamptz not null default now()
);

alter table public.site_analytics_events enable row level security;

create index if not exists site_analytics_events_event_created_idx
  on public.site_analytics_events (event_name, created_at desc);
create index if not exists site_analytics_events_product_created_idx
  on public.site_analytics_events (product_id, created_at desc);

-- Browser clients receive no direct table policy. Events are inserted only by the
-- Netlify function using the server-side Supabase service-role key.